### ISSUE TITLE
Are you sure branch master compiles?

### ISSUE THREAD

**Issue by heitorPB** [ngc92/stargame#3]
I am trying to make this code compile under linux, so far i added the irrlicht, irrKlang and Box2D. I am writting the makefile, but after some time, I get a very beautiful error with GCC 4.8:

> g++ -Wall -std=c++11 -pipe -fomit-frame-pointer -Iexternal/Box2D/Box2D/ -Iexternal/ -Isrc/ -c src/GameState/HUD.cpp -o obj/Release/HUD.o
> src/GameState/HUD.cpp: In member function ‘virtual void HUD::init()’:
> src/GameState/HUD.cpp:27:80: error: no matching function for call to ‘bind(<unresolved overloaded function type>, HUD\* const, const std::_Placeholder<1>&)’
>   mListeners.push_back(world().addSpawnListener(std::bind(HUD::onSpawn, this, _1)));
>                                                                                 ^
> src/GameState/HUD.cpp:27:80: note: candidates are:
> In file included from /usr/include/c++/4.8/mutex:42:0,
>                  from src/game/IGameViewModule.h:4,
>                  from src/game/CGameViewModule.h:4,
>                  from src/GameState/HUD.h:4,
>                  from src/GameState/HUD.cpp:1:
> /usr/include/c++/4.8/functional:1655:5: note: typename std::_Bind_helper<std::__or_<std::is_integral<typename std::decay<_Tp>::type>, std::is_enum<typename std::decay<_Tp>::type> >::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...) [with _Func = void (HUD::_)(const game::IGameObjectView&); _BoundArgs = {HUD_ const, const std::_Placeholder<1>&}; typename std::_Bind_helper<std::__or_<std::is_integral<typename std::decay<_Tp>::type>, std::is_enum<typename std::decay<_Tp>::type> >::value, _Func, _BoundArgs ...>::type = std::_Bind<std::_Mem_fn<void (HUD::*)(const game::IGameObjectView&)>(HUD_, std::_Placeholder<1>)>]
>      bind(_Func&& __f, _BoundArgs&&... __args)
>      ^
> /usr/include/c++/4.8/functional:1655:5: note:   no known conversion for argument 1 from ‘<unresolved overloaded function type>’ to ‘void (HUD::_&&)(const game::IGameObjectView&)’
> /usr/include/c++/4.8/functional:1682:5: note: template<class _Result, class _Func, class ... _BoundArgs> typename std::_Bindres_helper<_Result, _Func, _BoundArgs>::type std::bind(_Func&&, _BoundArgs&& ...)
>      bind(_Func&& __f, _BoundArgs&&... __args)
>      ^
> /usr/include/c++/4.8/functional:1682:5: note:   template argument deduction/substitution failed:
> src/GameState/HUD.cpp:27:80: note:   couldn't deduce template parameter ‘_Result’
>   mListeners.push_back(world().addSpawnListener(std::bind(HUD::onSpawn, this, _1)));
>                                                                                 ^
> make: **\* [src/GameState/HUD.o] Error 1

I will try later with another compiler.

**Comment by ngc92** [comment]
I am using 4.9, maybe they fixed some stdlib things...

Am 12.05.2016 um 15:35 schrieb heitorPB:

**Comment by ngc92** [comment]
you could also try to replace the std::bind, either with its boost 
equivalent, or by just writing the lambda yourself.

Am 12.05.2016 um 15:35 schrieb heitorPB:
